<?php
/**
 * Created by PhpStorm.
 * User: seven
 * Date: 2019/2/2
 * Time: 23:17
 */

namespace Tests\KickPeach\Queue;

use KickPeach\Queue\Drivers\Beanstalkd;
use KickPeach\Queue\Queue;
use KickPeach\Queue\Worker;
use PHPUnit\Framework\TestCase;
use Tests\KickPeach\Queue\Jobs;

class QueueTest extends TestCase
{
    /**
     * @var Queue
     */
    private $queue;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $host = 'localhost';
        $port = 11300;
        $this->queue = new Queue(new Beanstalkd($host, $port));
    }

    public function testDispatch()
    {
        $job = new Jobs\ExampleJob([1, 2, 3, 0, 6]);

        $this->queue->push($job);
    }

    public function _testLater()
    {
        $job = new Jobs\ExampleJob([1, 2, 3, 0, 6]);

        $this->queue->later(60, $job);
    }

    public function testRunNextJob()
    {
        $worker = new Worker($this->queue);

        $worker->runNextJob();
    }

}